environment: production # minifier needs it it

# Directories
source:          .
destination:     _site
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes
collections_dir: _collections

# Collections
collections:
  software:
    output: false

# General
title: Raphael Menges
description: > # this means to ignore newlines
  Homepage of Raphael Menges
plugins: ['jekyll-scholar', 'jekyll-minimagick']
baseurl: "" # must be empty string
permalink: pretty
markdown: kramdown

# Compilation
liquid:
  strict_variables: true
  strict_filters: true

# Excludes
exclude:
  - .gitignore
  - .bundle
  - .github
  - README.md
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock

# Thumbnails
mini_magick:
  thumbnail:
    source: assets/imgs
    destination: assets/imgs/thumbs
    resize: "600x60" # maximum dimension, original aspect ratio is kept

# Jekyll-Scholar
scholar:
  source: _bibliography
  bibliography: references.bib
  reference_tagname: span
  style: acm-siggraph
  sort_by: year,month
  group_order: descending # order of groups
  order: desceding # order within group
  group_by: year
  bibliography_template: ref # how to render a reference
  details_layout: 'bib.html' # layout for page generated per entry
  details_link: 'BibTeX' # how the link to the generated pages is called
  repository: ./assets/pubs
  bibliography_group_tag: h3

# Meta info about publications
pubs:
  menges2019iue:
    authorizer_link: 'https://dl.acm.org/authorize?N690524'
    select: true
    images: ['iue_pd.jpg', 'iue_web_extraction.jpg', 'iue_keyboard_hebrew.jpg', 'iue_youtube.jpg']
  kumar2017cbf:
    award: 'Honourable Mention'
  menges2017ggw:
    award: 'Judges Award at TPG Accessibility Challenge'
    video: 'https://youtu.be/x1ESgaoQR9Y'
  menges2018erw:
    award: 'Best Video Award (for accompanying video)'
    select: true
    images: ['erw_problems.jpg', 'erw_enhanced_representation.jpg', 'erw_screenshot.jpg']
    video: 'https://youtu.be/SXLE9xM5P2c'
  sengupta2017aic:
    award: 'Best Student Paper Award'
  lichtenberg2018ars:
    images: ['ars_overview.jpg', 'ars_example.jpg']
  schaefer2014sga:
    video: 'https://youtu.be/nB6fQ-310lg'
  sengupta2017gik:
    video: 'https://youtu.be/-UDDTJHBPVA'
  menges2017sgc:
    video: 'https://youtu.be/WOcb94t6BaQ'
  kumar2017aug:
    video: 'https://youtu.be/NQQfB7nf3qw'
  sengupta2018hwb:
    video: 'https://youtu.be/M0hHakm36y0'
  menges2016enf:
    video: 'https://youtu.be/niMRX65E7IE'
  kumar2019tgp:
    video: 'https://youtu.be/dWWD1fVMAi0'

# Meta information about academia
academia:
  master:
    images: ['master_ui1.jpg', 'master_ui2.jpg', 'master_surface.jpg', 'master_impl.jpg', 'master_ascension.jpg']
  bachelor:
    images: ['bachelor_ui.jpg', 'bachelor_jittering.jpg', 'bachelor_shadows.jpg', 'bachelor_transferfunction.jpg', 'bachelor_evaluation.jpg']

# Meta information about jobs
jobs:
  mamem:
    images: ['mamem_second_trials.jpg', 'mamem_meeting.jpg']
  gazemining:
    images: ['gazemining_poster.jpg', 'gazemining_etra.jpg', 'gazemining_mittelstandskonferenz.jpg']