environment: production

# Directories
source:          .
destination:     _site
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes
collections_dir: _collections

# General
title: Raphael Menges
description: > # this means to ignore newlines
  Homepage of Raphael Menges
plugins: ['jekyll-scholar']
baseurl: "" # must be empty string
permalink: pretty
markdown: kramdown

# Compilation
liquid:
  strict_variables: true
  strict_filters: true

# Excludes
exclude:
  - README.md
  - .gitignore
  - docs
  - .bundle
  - vendor
  - Gemfile
  - Gemfile.lock

# Jekyll-Scholar
scholar:
  source: _bibliography
  bibliography: references.bib
  reference_tagname: span
  style: acm-siggraph
  sort_by: year,month
  group_order: descending # order of groups
  order: desceding # order within group
  group_by: year
  bibliography_template: ref # how to render a reference
  details_layout: 'bib.html' # layout for page generated per entry
  details_link: 'BibTeX' # how the link to the generated pages is called
  # details_layout
  repository: ./assets/pubs
  bibliography_group_tag: h3

# Authorize links
authorizer_link:
  menges2019iue: 'https://dl.acm.org/authorize?N690524'