name: Build the site

on:
  push:
    branches:
      - dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # Checkout the master branch (github-pages-deploy-action switches itself to dev branch)
    - name: Checkout
      uses: actions/checkout@master

    # Build the dev branch and force push it to master
    - name: Build and Force Push
      uses: JamesIves/github-pages-deploy-action@releases/v2 # takes ubuntu latest. Docker image with ruby would be much better
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: dev # this is the branch where the actual code is
        BRANCH: gh-pages # here is the generated site
        FOLDER: _site # Jekyll standard output
        BUILD_SCRIPT: apt update
                      && apt -yq install ruby-full
                      && gem install bundler
                      && bundle install --path vendor
                      && bundle exec jekyll build