name: Build and deploy site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup imagemagick
      uses: mfinelli/setup-imagemagick@v6

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
        bundler-cache: true

    - name: Build
      run: |
        bundle install --path vendor
        bundle exec jekyll build
        npm install html-minifier -g
        html-minifier --input-dir ./_site --output-dir ./_site --remove-comments --collapse-whitespace --minify-js --minify-css --file-ext html
        html-minifier --input-dir ./_site --output-dir ./_site --remove-comments --collapse-whitespace --minify-js --minify-css --file-ext css
        mv archive _site/

    - name: Force push to gh_pages branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh_pages
        folder: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Trigger page update
      run: |
        git clone https://action:${{ secrets.ACCESS_TOKEN }}@github.com/raphaelmenges/raphaelmenges.github.io.git
        cd raphaelmenges.github.io
        git checkout master
        git config --global user.email "action@github.com"
        git config --global user.name "action"
        git commit -m 'rebuild pages' --allow-empty
        git push origin master
