name: Build and deploy to GitHub pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master 
          
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2.0.3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: _site
        BUILD_SCRIPT: bundle install --path vendor && bundle exec jekyll serve
